# docker-compose up -d

# version: '3.8'

# services:
#   postgres_db:
#     image: postgres:latest
#     environment:
#       POSTGRES_USER: ${DB_USER}
#       POSTGRES_PASSWORD: ${DB_PASSWORD}
#       POSTGRES_DB: ${DB_NAME}
#     ports:
#       - "${DB_PORT}:5432"
#     # volumes:
#     #    - ./init.sql:/docker-entrypoint-initdb.d/init.sql

#   app:
#     build: .
#     container_name: fastapi_app
#     ports:
#       - "8000:8000"
#     depends_on:
#       - postgres_db
#     volumes:
#       - .:/app
#       - ./templates:/app/templates

version: "3.9"

services:
  ppoisdb:
    image: "postgres:latest"
    container_name: fastapi_app
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}  
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER:  ${DB_USER}
    volumes:
      - 'ppois-db-data:/var/opt/mssql'

 
volumes:
  ppois-db-data:
    driver: local